#!/bin/bash
#Script to play YouTube using OMXPlayer
echo "Loading YouTube Videos..."
history=/tmp/OMXhist
cp ~/.config/chromium/Default/History $history
tmpfile=$(tempfile --prefix=OMXt_)
omxplayer=omxplayer
#omxopts="-r -o hdmi"
cookiefile="/tmp/cookies-$( date +%s.%N ).txt";
omxurls="$HOME/.omxtube.urls"
while [ $# -gt 0 ]; do
    case $1 in
	-mplayer)
	    omxplayer=mplayer
	    omxopts="-ao alsa -vo novideo -cookies -cookies-file $cookiefile"
	    ;;
	-vlc)
	    omxplayer=nvlc
	    omxopts="--no-video --one-instance --playlist-enqueue"
	    xterm -e screen nvlc $omxopts &
	    sleep 2
	    ;;
	-aud)
	    omxplayer=audacious
	    omxopts="--enqueue"
	    audacious &
	    sleep 2
	    ;;
	-url)
	    shift
	    if [ -z "$1" ]; then
		[ -f $omxurls ] && cat $omxurls
		echo -n "URL: "
		read url
	    else
		url="$1"
	    fi
	    sedex=`echo "$url" |sed -r 's:.*(v=[^\& ]+).*:/\1/d:'` && echo "$sedex"
	    [ -f $omxurls ] && sed -ri "$sedex" $omxurls
	    echo "$url" >>$omxurls
	    url=${url/ #*/}
    esac
    shift
done
echo "omxplayer: $omxplayer"
echo "omxopts: '$omxopts'"

#url=$(sqlite3 $history 'SELECT url FROM urls ORDER BY last_visit_time DESC LIMIT 1')
[ -z "$url" ] && \
url=$(sqlite3 $history 'SELECT url FROM urls ORDER BY last_visit_time' |grep '^http[s]*://www.youtube.com/' |tail -1)
case $url in
  *[\&\?]list=*) pl=true
	;;
  *) pl=false
	;;
esac
[ -n "$DISPLAY" ] && xset -dpms
#sel_url="grep mime.audio"
sel_url="grep audio"
if $($pl); then
i=0
st=0
echo "$url"
while [ $i -lt 1 -o -n "$dlurl" -o $st -gt 0 ]; do
  i=$[i+1]
#  dlurl=$(youtube-dl --playlist-start=$i --playlist-end=$i --max-quality 35 -g "$url")
  dlurl=$(youtube-dl --playlist-start=$i --playlist-end=$i -f 18 -g "$url" |$sel_url |head -1)
  st=$?
  if [ -n "$dlurl" ]; then
    echo "$i: $dlurl" && $omxplayer $omxopts "$dlurl"
    [ -n "$DISPLAY" ] && xrefresh -display :0
  fi
done
else
  dlurl=$(youtube-dl --cookies $cookiefile -f 18 -g "$url" |$sel_url |head -1)
  echo "$dlurl"
  $omxplayer $omxopts "$dlurl"
  [ -n "$DISPLAY" ] && xrefresh -display :0
fi
rm $history $tmpfile $cookiefile
[ -n "$DISPLAY" ] && xset +dpms
echo -n "Press ENTER!"
read
